// Code generated by protoc-gen-go. DO NOT EDIT.
// source: solver.proto

package solver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SolveRequest struct {
	KeyStart             int64    `protobuf:"varint,1,opt,name=key_start,json=keyStart,proto3" json:"key_start,omitempty"`
	KeyEnd               int64    `protobuf:"varint,2,opt,name=key_end,json=keyEnd,proto3" json:"key_end,omitempty"`
	Step                 int64    `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	Problem              int64    `protobuf:"varint,4,opt,name=problem,proto3" json:"problem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolveRequest) Reset()         { *m = SolveRequest{} }
func (m *SolveRequest) String() string { return proto.CompactTextString(m) }
func (*SolveRequest) ProtoMessage()    {}
func (*SolveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{0}
}

func (m *SolveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolveRequest.Unmarshal(m, b)
}
func (m *SolveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolveRequest.Marshal(b, m, deterministic)
}
func (m *SolveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolveRequest.Merge(m, src)
}
func (m *SolveRequest) XXX_Size() int {
	return xxx_messageInfo_SolveRequest.Size(m)
}
func (m *SolveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SolveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SolveRequest proto.InternalMessageInfo

func (m *SolveRequest) GetKeyStart() int64 {
	if m != nil {
		return m.KeyStart
	}
	return 0
}

func (m *SolveRequest) GetKeyEnd() int64 {
	if m != nil {
		return m.KeyEnd
	}
	return 0
}

func (m *SolveRequest) GetStep() int64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *SolveRequest) GetProblem() int64 {
	if m != nil {
		return m.Problem
	}
	return 0
}

type SolveResponse struct {
	Solution             int64    `protobuf:"varint,1,opt,name=solution,proto3" json:"solution,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SolveResponse) Reset()         { *m = SolveResponse{} }
func (m *SolveResponse) String() string { return proto.CompactTextString(m) }
func (*SolveResponse) ProtoMessage()    {}
func (*SolveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7779dcc6dfedf133, []int{1}
}

func (m *SolveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SolveResponse.Unmarshal(m, b)
}
func (m *SolveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SolveResponse.Marshal(b, m, deterministic)
}
func (m *SolveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SolveResponse.Merge(m, src)
}
func (m *SolveResponse) XXX_Size() int {
	return xxx_messageInfo_SolveResponse.Size(m)
}
func (m *SolveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SolveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SolveResponse proto.InternalMessageInfo

func (m *SolveResponse) GetSolution() int64 {
	if m != nil {
		return m.Solution
	}
	return 0
}

func init() {
	proto.RegisterType((*SolveRequest)(nil), "solver.SolveRequest")
	proto.RegisterType((*SolveResponse)(nil), "solver.SolveResponse")
}

func init() { proto.RegisterFile("solver.proto", fileDescriptor_7779dcc6dfedf133) }

var fileDescriptor_7779dcc6dfedf133 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xc1, 0xca, 0x82, 0x40,
	0x14, 0x85, 0x7f, 0x7f, 0x4d, 0xed, 0x62, 0x9b, 0x4b, 0xd1, 0x60, 0x9b, 0x70, 0x15, 0x04, 0x2e,
	0x0a, 0x7a, 0x83, 0x68, 0xaf, 0x0f, 0x10, 0x99, 0x77, 0x21, 0xda, 0xcc, 0x34, 0x33, 0x0a, 0xbe,
	0x7d, 0x38, 0x2a, 0x44, 0xbb, 0xfb, 0x7d, 0xe7, 0xc2, 0xe1, 0x40, 0xa4, 0x45, 0xd3, 0x91, 0x4a,
	0xa5, 0x12, 0x46, 0xa0, 0x3f, 0x52, 0xa2, 0x20, 0xca, 0x87, 0x2b, 0xa3, 0x77, 0x4b, 0xda, 0xe0,
	0x0e, 0x96, 0x35, 0xf5, 0x77, 0x6d, 0x1e, 0xca, 0x30, 0x67, 0xef, 0x1c, 0xdc, 0x2c, 0xac, 0xa9,
	0xcf, 0x07, 0xc6, 0x2d, 0x04, 0x43, 0x48, 0xbc, 0x64, 0xff, 0x36, 0xf2, 0x6b, 0xea, 0xaf, 0xbc,
	0x44, 0x04, 0x4f, 0x1b, 0x92, 0xcc, 0xb5, 0xd6, 0xde, 0xc8, 0x20, 0x90, 0x4a, 0x14, 0x0d, 0xbd,
	0x98, 0x67, 0xf5, 0x8c, 0xc9, 0x11, 0x56, 0x53, 0xa7, 0x96, 0x82, 0x6b, 0xc2, 0x18, 0x42, 0x2d,
	0x9a, 0xd6, 0x54, 0x82, 0xcf, 0x9d, 0x33, 0x9f, 0x6e, 0xd3, 0xb3, 0xca, 0x49, 0x75, 0xd5, 0x93,
	0xf0, 0x02, 0x0b, 0x2b, 0x70, 0x9d, 0x4e, 0x8b, 0xbe, 0x07, 0xc4, 0x9b, 0x1f, 0x3b, 0x56, 0x24,
	0x7f, 0x85, 0x6f, 0x87, 0x9f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xc9, 0xa1, 0x57, 0x08,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SolverServiceClient is the client API for SolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SolverServiceClient interface {
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
}

type solverServiceClient struct {
	cc *grpc.ClientConn
}

func NewSolverServiceClient(cc *grpc.ClientConn) SolverServiceClient {
	return &solverServiceClient{cc}
}

func (c *solverServiceClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, "/solver.SolverService/Solve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolverServiceServer is the server API for SolverService service.
type SolverServiceServer interface {
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
}

func RegisterSolverServiceServer(s *grpc.Server, srv SolverServiceServer) {
	s.RegisterService(&_SolverService_serviceDesc, srv)
}

func _SolverService_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolverServiceServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/solver.SolverService/Solve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolverServiceServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SolverService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "solver.SolverService",
	HandlerType: (*SolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _SolverService_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "solver.proto",
}
